services:
  # --- NOVO SERVIÇO: Ponte MQTT (Python) ---
  mqtt-bridge:
    build: ./mqtt-bridge                # Pasta onde devem estar o main.py e o Dockerfile do conversor
    container_name: intiniftyclone
    restart: unless-stopped
    environment:
      MQTT_BROKER: cerise.freeddns.org
      MQTT_PORT: 30001
      MQTT_USER: infinitwin_user
      MQTT_PASS: IwtLab#2025!